# version: '3.8'
services:
  app:
    image: my-go-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/mydb?sslmode=disable
    # depends_on:
    #   db:
    #     condition: service_healthy
    # networks:
    #   - app-network

  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

# volumes:
#   postgres-data:

# networks:
#   app-network:
#     driver: bridge