apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: default
spec:
  selector:
    app: product-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080