name: ci-test

on:
  push:
    branches: [ main]
  pull_request:
    branches: [main]


  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: zitadel

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: "1.22"

        - name: Intall dependencies
          run: go mod download

        - name: Run tests
          run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            token: ./coverage.txt